- name: script module
  script: test.sh
  tags: script_mod

- name: shell module ex1
  shell: cat /home/dir1/file1
  register: shell_out_cat
  tags: shell_mod

- name: show shell_out_cat
  debug:
    msg: "{{shell_out_cat.stdout}}"
  tags: shell_mod

- name: shell module ex2
  shell: ps -aux
  register: shell_out_ps
  tags: shell_mod

- name: show shell_out_ps
  debug:
    msg: "{{shell_out_ps.stdout}}"
  tags: shell_mod

- name: shell module ex3
  shell: curl -v https://anisa.co.ir
  register: shell_out_cr
  tags: shell_mod

- name: show shell_out_cr
  debug:
    msg: "{{shell_out_cr.stdout}}"
  tags: shell_mod

- name: copy module 
  copy:
    src: test.txt
    dest: /home/dir1/
    owner: root
    group: root
    mode: 0644
  tags: copy_mod_1

- name: copy module with force no
  copy:
    src: test.txt
    dest: /home/dir1/
    owner: root
    group: root
    mode: 0644
    force: no
  tags: copy_mod_2

- name: copy module with backup yes
  copy:
    src: test.txt
    dest: /home/dir1
    owner: root
    group: root
    mode: 0644
    force: yes
    backup: yes
  tags: copy_mod_3

- name: copy module with remote src
  copy:
    src: /home/dir1/test.txt
    dest: /home/
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  tags: copy_mod_4

- name: fetch module
  fetch:
    src: /home/dir1/file1
    dest: /home
  tags: fetch_mod

- name: fetch module with flat yes
  fetch:
    src: /home/dir1/file1
    dest: /home/
    flat: yes
    validate_checksum: no
  tags: fetch_mod_1

- name: group module 
  group:
    name: devops
    state: present
  tags: group_mod

- name: user module
  user:
    name: arya
    group: devops
    state: present
    shell: /bin/bash
    home: /tmp/arya
  tags: user_mod

- name: expect mod
  expect:
    command: passwd arya
    responses:
      password: "123"
  no_log: true
  tags: expect_mod

- name: zypper repository module
  zypper_repository:
    name: ansible
    repo: /opt/Ansible
    state: present
  tags: zypp_mod

- name: zypper module
  zypper:
    name: 'http://nginx.org/packages/sles/12/x86_64/RPMS/nginx-1.8.0-1.sles12.ngx.x86_64.rpm'
    state: present
    disable_gpg_check: yes
  tags: zypper_mod

- name: yum repository module 
  yum_repository:
    name: epel
    description: extra packages
    baseurl: https://download.fedoraproject.org/pub/epel/$releaseever/$basearch
    gpgcheck: no
    enabled: yes
    state: present
  tags: yum_repo_mod

- name: yum module 
  yum:
    name: nginx 
    state: present
  tags: yum_mod

- name: update nginx
  yum:
    name: nginx
    state: latest
    update_only: yes
  tags: yum_mod_1

- name: update all packages
  yum:
    name: '*'
    state: latest
  tags: update_all_packages

- name: update all packages except kernel related packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  tags: update_packages
~                 
